### ISSUE TITLE
关于程序中缺失的文件

### ISSUE THREAD

**Issue by APPLE-XMT** [guzy0324/meta_learned_review_helpfulness_prediction#1]
您好，请问一下程序中的这个问题：No module named 'pytorch_lightning'，这个模块是要自己写吗？

**Comment by guzy0324** [comment]
请按照readme指引配置环境

**Comment by guzy0324** [comment]
> 您好，请问一下程序中的这个问题：No module named 'pytorch_lightning'，这个模块是要自己写吗？

您好，请问问题解决了吗，解决了我会关闭问题

**Comment by APPLE-XMT** [comment]
> 好，请问问题解决了吗，解决了我会关闭问题

您好，我按照您写的readme重新配置了环境，已经解决了这个问题，感谢您的指导！
